type: mpc
pi: 3.14159
mpc:
  model_name: pointRobot
  solver_name: pointRobot_fixed_solver
  n: 3
  nu: 4
  time_horizon: 22
  time_step: 0.1
  slack: False
  interval: 1
  initialization: 'current_state'
  interactive: True
  constraints:
    - SelfCollisionAvoidanceConstraints
    - JointLimitConstraints
    - InputLimitConstraints
    - VelLimitConstraints
  objectives:
    - GoalReaching
  weights:
    Wgoal_position: 1
    Wgoal_orientation: 0
    Wvel_orientation: 0
    Wa: 0.01
    Wv: 0
  n_static_obst: 1
  n_dynamic_obst: 1
  control_mode: "acc"
  python_version: '<3.10'
pedestrians:
  radius: 0.4
  sfm:
    desired_speed: 1.4
    w_goal : 1
    w_social : 1
    w_obstacle: 0
  state_constraints:
    lower_bounds:
      x: -20
      y: -20
      psi: -6.3
      v_x: -1.5
      v_y: -1.5
      w: -1
    upper_bounds:
      x: 20
      y: 20
      psi: 6.3
      v_x: 1.5
      v_y: 1.5
      w: 1
  input_constraints:
    lower_bounds:
      a_x: -3
      a_y: -3
      alpha: -1
      slack: 0
    upper_bounds:
      a_x: 3
      a_y: 3
      alpha: 1
      slack: 0.2
robot:
  robot_name: dingo
  radius: 0.4
  state_constraints:
      lower_bounds:
        x: -20
        y: -20
        psi: -6.3
        v_x: -1.2
        v_y: -1.2
        w: -1
      upper_bounds:
        x: 20
        y: 20
        psi: 6.3
        v_x: 1.2
        v_y: 1.2
        w: 1
  input_constraints:
      lower_bounds:
        a_x: -0.5
        a_y: -0.5
        alpha: -1
        slack: 0
      upper_bounds:
        a_x: 0.5
        a_y: 0.5
        alpha: 1
        slack: 0.2
  collision_links:
    - base_link
  selfCollision:
    pairs:  []
  urdf_file: pointRobot.urdf
  root_link: ee_link
  end_link: base_link
  base_type: holonomic
example:
  debug: False
env:
  dt: 0.1
  robot:
    radius: 0.4
    state_constraints:
      lower_bounds:
        x: -20
        y: -20
        psi: -6.3
        v_x: -1.2
        v_y: -1.2
        w: -1
      upper_bounds:
        x: 20
        y: 20
        psi: 6.3
        v_x: 1.2
        v_y: 1.2
        w: 1
    input_constraints:
      lower_bounds:
        a_x: -0.5
        a_y: -0.5
        alpha: -1
        slack: 0
      upper_bounds:
        a_x: 0.5
        a_y: 0.5
        alpha: 1
        slack: 0.2
  pedestrian:
    radius: 0.4
    sfm:
      desired_speed: 1.4
      w_social: 1
      w_goal: 1
    state_constraints:
      lower_bounds:
        x: -20
        y: -20
        psi: -6.3
        v_x: -1.5
        v_y: -1.5
        w: -1
      upper_bounds:
        x: 20
        y: 20
        psi: 6.3
        v_x: 1.5
        v_y: 1.5
        w: 1
    input_constraints:
      lower_bounds:
        a_x: -3
        a_y: -3
        alpha: -1
        slack: 0
      upper_bounds:
        a_x: 3
        a_y: 3
        alpha: 1
        slack: 0.2